language: ruby
sudo: false
services:
  - mongodb
rvm:
  - 2.0
  - 2.1
  - 2.2.3
  - 2.3.0
  # - rbx
gemfile:
  - gemfiles/rails.3.2.activerecord.gemfile
  - gemfiles/rails.3.2.activerecord.kaminari.gemfile
  - gemfiles/rails.3.2.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.0.activerecord.gemfile
  - gemfiles/rails.4.0.activerecord.kaminari.gemfile
  - gemfiles/rails.4.0.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.1.activerecord.gemfile
  - gemfiles/rails.4.1.activerecord.kaminari.gemfile
  - gemfiles/rails.4.1.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.2.activerecord.gemfile
  - gemfiles/rails.4.2.activerecord.kaminari.gemfile
  - gemfiles/rails.4.2.activerecord.will_paginate.gemfile
  - gemfiles/rails.5.0.0.beta3.activerecord.gemfile
  - gemfiles/rails.5.0.0.beta3.activerecord.kaminari.gemfile
  - gemfiles/rails.5.0.0.beta3.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.0.mongoid.4.0.0.gemfile
  - gemfiles/rails.4.0.mongoid.4.0.0.kaminari.gemfile
  - gemfiles/rails.4.0.mongoid.4.0.0.will_paginate.gemfile
  - gemfiles/rails.4.0.mongoid.5.1.0.gemfile
  - gemfiles/rails.4.0.mongoid.5.1.0.kaminari.gemfile
  - gemfiles/rails.4.0.mongoid.5.1.0.will_paginate.gemfile
  - gemfiles/rails.4.1.mongoid.4.0.0.gemfile
  - gemfiles/rails.4.1.mongoid.4.0.0.kaminari.gemfile
  - gemfiles/rails.4.1.mongoid.4.0.0.will_paginate.gemfile
  - gemfiles/rails.4.1.mongoid.5.1.0.gemfile
  - gemfiles/rails.4.1.mongoid.5.1.0.kaminari.gemfile
  - gemfiles/rails.4.1.mongoid.5.1.0.will_paginate.gemfile
  - gemfiles/rails.4.2.mongoid.4.0.0.gemfile
  - gemfiles/rails.4.2.mongoid.4.0.0.kaminari.gemfile
  - gemfiles/rails.4.2.mongoid.4.0.0.will_paginate.gemfile
  - gemfiles/rails.4.2.mongoid.5.1.0.gemfile
  - gemfiles/rails.4.2.mongoid.5.1.0.kaminari.gemfile
  - gemfiles/rails.4.2.mongoid.5.1.0.will_paginate.gemfile
  - gemfiles/sequel.4.31.gemfile

matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails.5.0.0.beta3.activerecord.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails.5.0.0.beta3.activerecord.kaminari.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails.5.0.0.beta3.activerecord.will_paginate.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails.5.0.0.beta3.activerecord.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails.5.0.0.beta3.activerecord.kaminari.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails.5.0.0.beta3.activerecord.will_paginate.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails.3.2.activerecord.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails.3.2.activerecord.kaminari.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails.3.2.activerecord.will_paginate.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails.3.2.activerecord.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails.3.2.activerecord.kaminari.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails.3.2.activerecord.will_paginate.gemfile
before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.2.tar.gz | tar xz -C /tmp
before_script:
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-2.3.2/bin/elasticsearch" rake elasticsearch:start
